use_frameworks!

platform :ios, '13.0'

target 'ScreenMeetSDK_Example' do
  pod 'ScreenMeetSDK'

  target 'ScreenMeetSDK_Tests' do
    inherit! :search_paths

    
  end
end

target 'FullExample' do
  pod 'ScreenMeetSDK'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
    # Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_IDENTITY[sdk=ios*]'] = '-'
        end
    end
  end
end
