use_frameworks!

platform :ios, '13.0'

target 'ScreenMeetSDK_Example' do
  pod 'ScreenMeetSDK', :path => '../'

  target 'ScreenMeetSDK_Tests' do
    inherit! :search_paths

    
  end
end

target 'FullExample' do
  pod 'ScreenMeetSDK', :path => '../'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
